version: "3.9"

services:
  slackbot:
    build: .
    ports:
      - ${DB_PORT}:5001

    environment:
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      PORT: ${DB_PORT}
      AXIOM_NEMO_SLACKBOT_API_TOKEN: ${AXIOM_NEMO_SLACKBOT_API_TOKEN}
      AXIOM_PERSONAL_TOKEN: ${AXIOM_PERSONAL_TOKEN}
      AXIOM_ORG_ID: ${AXIOM_ORG_ID}
      GOOGLE_CALENDAR_API_KEY: ${GOOGLE_CALENDAR_API_KEY}
      GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
      SANITY_PROJECT_ID: ${SANITY_PROJECT_ID}
